version: '3.7'

services:
  # web:
  #  build:
  #    context: ./react
  #    dockerfile: Dockerfile
  #  expose:
  #    - '80'
  #  volumes:
  #    - ~/Projects/lost_cities/react:/app
  #  environment:
  #     VIRTUAL_HOST: localhost,www.localhost
  #     VIRTUAL_PORT: 3000

  api:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./flask:/usr/src/app
    environment:
      - FLASK_APP=src


# networks:
#     default:
#        external:
#          name: nginx-proxy
