version: '3.5'

services:
  lostcities_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    expose:
      - 5000
    volumes:
      - ./api:/usr/src/app
    environment:
      - FLASK_APP=src:create_app()
      - FLASK_ENV=production
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@lostcities_db:5432/lostcities_dev
    depends_on:
      - lostcities_db

  lostcities_db:
    build:
      context: ./api/db
      dockerfile: Dockerfile
    ports:
        - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  default:
    external:
      name: nginx_proxy
    
