version: '3.5'

services:

  lostcities_api:
    build:
      context: ./api
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    expose:
      - 5000
    environment:
      - SECRET_KEY=testingprodsecretkey
      - APP_SETTINGS=src.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@lostcities_db:5432/lostcities_prod
    depends_on:
      - lostcities_db
    
  lostcities_db:
    build:
      context: ./api/db
      dockerfile: Dockerfile
    restart: unless-stopped    
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  default:
    external:
      name: nginx_proxy