version: '3.7'

services:
  client:
    build:
      context: ./react
      dockerfile: Dockerfile-prod
      # args:
      #   - REACT_APP_API_URL:http://lostcities.local/api
    restart: unless-stopped
    expose:
      - 80 
    depends_on:
      - api

  api:
    build:
      context: ./flask
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    expose:
      - 5000
    environment:
      - SECRET_KEY=testingprodsecretkey
      - APP_SETTINGS=src.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/lostcities_prod
    depends_on:
      - db
    
  db:
    build:
        context: ./flask/db
        dockerfile: Dockerfile
    restart: unless-stopped    
    expose:
        - 5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
      - client
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"