version: '3.5'

services:
  # web:
  #   build:
  #     context: ./react
  #     dockerfile: Dockerfile.prod
  #   restart: unless-stopped
  #   logging:
  #     driver: syslog
  #   expose:
  #     - '80'
      
  api:
    build:
      context: ./flask
      dockerfile: Dockerfile-prod
    restart: unless-stopped    
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=src.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/lostcities_prod
    depends_on:
      - db
    
  db:
    build:
        context: ./flask/db
        dockerfile: Dockerfile
    expose:
        - 5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
